username = input("Введите ваше имя: ")
title = input("Введите заголовок заметки: ")
content = input("Введите описание заметки: ")
status = input("Введите статус заметки: ")
created_date = input("Введите дату создания заметки (ДД.ММ.ГГГГ): ")
issue = input("Введите дату истечения заметки (ДД.ММ.ГГГГ): ")
title1 = input("Введите заголовок 1: ")
title2 = input("Введите заголовок 2: ")
print("Имя пользователя:", username)
print("Заголовок заметки",title)
print("Описание заметки",content)
print("Статус заметки", status)
print("Дата создания заметки",created_date)
print("Дата истечения заметки", issue)
print("Заголовок 1", title1)
print("Заголовок 2", title2)